apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-static
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KubeCraftsMan/k8s-multitier-kind.git
    targetRevision: HEAD
    path: k8s/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
